name: ampratio
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - obspy
  - jupyter
  - scipy
  - tqdm
  - basemap
  - ipython
  - ipykernel
  - ipywidgets
  - notebook
  - pip
